### ISSUE TITLE
Why you use bootstrapcdn? 

### ISSUE THREAD

**Issue by mrm7moud** [FACG2/BayMax#20]
You used bootstrap cdn for style

https://github.com/FACG2/BayMax/blob/master/index.html#L12

https://github.com/FACG2/BayMax/blob/master/index.html#L14

**Comment by Walidmash** [comment]
It is not a bootstrap, it a font (font-awesome) to add the icons of facebook ...
We asked the mentors if its allowed to use it or not , and they said yes :)
